### PR TITLE
hotfix for `RMatrix`'s `new_matrix`

### PR DESCRIPTION
**Pull request by CGMossa**
There is an issue in using `RMatrix::new_matrix`. This is likely due to `mut`-correctness introduced in #644

There are a few more areas where this is present.

This wasn't captured by our test suite, for reasons that I cannot comprehend. 

```
   Compiling arcpbf v0.1.0 (C:\Users\minin\Documents\GitHub\arcpbf\src\rust\arcpbf)
error[E0596]: cannot borrow data in dereference of `RArray<f64, [usize; 2]>` as mutable
  --> arcpbf\src\geometry\point.rs:40:5
   |
40 |     RMatrix::new_matrix(decoded.len(), 2, |r, c| decoded[r][c])
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
   |
   = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `RArray<f64, [usize; 2]>`

For more information about this error, try `rustc --explain E0596`.
error: could not compile `arcpbf` (lib) due to previous error
```

The code in question

```rs

pub fn read_multipoint(x: Option<CompressedGeometry>, trans: &Translate, scale: &Scale) -> Robj {
    if x.is_none() {
        let empty_mpnt = Doubles::new(0)
            .into_robj()
            .set_attrib("dim", Integers::from_values([0, 2]))
            .unwrap();
        return empty_mpnt;
    }

    let mut crds = match x.unwrap() {
        CompressedGeometry::Geometry(g) => g.coords,
        CompressedGeometry::ShapeBuffer(_) => todo!(),
    };

    let decoded = delta_decode(&mut crds, trans, scale);

    RMatrix::new_matrix(decoded.len(), 2, |r, c| decoded[r][c])
        .set_class(&["XY", "MULTIPOINT", "sfg"])
        .unwrap()
}

```

### CODE REVIEW

**Comment by CGMossa** [comment]
@Ilia-Kosenkov this is a little urgent, as it simply won't compile code that used to compile, and the user cannot fix it on their end.

**Comment by JosiahParry** [comment]
It is urgent in the sense of "dont publish a new release without fixing this" 😝 
Good catch @CGMossa !!

**Review by Ilia-Kosenkov — APPROVED** [review]

**Comment by CGMossa** [comment]
@Ilia-Kosenkov thanks for approving even late into the night. I appreciate that.
But there was a follow-up here and it is... what is our tests missing? Why does this code evoke a `DerefMut`? If
you can figure out, please tell, because then I need to make a teeest for that :P
